// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./ComponentLabel.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const ComponentLabelContext = createContext(null);

function ComponentLabel(_props) {
  const defaults = useContext(ComponentLabelContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="AzpHMHoEUA"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "AzpHMHoEUA",
        scope: "N1PcfSVoYd",
        activeVariants: activeVariants,
      }}
    >
      <ContainerPrimitive
        key={"3374sFSZZ9"}
        id={"Slot_3374sFSZZ9"}
        className={
          "__visly_reset_7X7HTLRqyD __visly_scope_N1PcfSVoYd_3374sFSZZ9"
        }
        addSpacing={false}
      >
        {props.label}
      </ContainerPrimitive>
      <SpacerPrimitive
        id={"Spacer_8byXZzcz4J"}
        className={
          "__visly_reset_7X7HTLRqyD __visly_scope_N1PcfSVoYd_8byXZzcz4J"
        }
        key={"8byXZzcz4J"}
      />
      <ContainerPrimitive
        key={"qMkJiZVVpu"}
        id={"Slot_qMkJiZVVpu"}
        className={
          "__visly_reset_7X7HTLRqyD __visly_scope_N1PcfSVoYd_qMkJiZVVpu"
        }
        addSpacing={false}
      >
        {props.control}
      </ContainerPrimitive>
    </RootPrimitive>
  );
}

ComponentLabel.__variants = [];

export default ComponentLabel;
