// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./Header.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, SpacerPrimitive } from "./_internal_primitives";
import { default as Title, TitleContext } from "./Title";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {},
      },
    ],
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      SuvZDMdpcu: {},
    },
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {
          SuvZDMdpcu: {},
        },
      },
      {
        propValue: "large",
        layers: {
          SuvZDMdpcu: {},
        },
      },
      {
        propValue: "medium",
        layers: {
          SuvZDMdpcu: {},
        },
      },
    ],
  },
];

const variantPropTypes = [
  {
    type: "enum",
    propName: "size",
    propValues: ["small", "large", "medium"],
  },
];

export const HeaderContext = createContext(null);

function Header(_props) {
  const defaults = useContext(HeaderContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="4LjcWAtK4B"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "4LjcWAtK4B",
        scope: "7dLna7xm52",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        <SpacerPrimitive
          id={"Spacer_P4bvLAfFvX"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_7dLna7xm52_P4bvLAfFvX"
          }
          key={"P4bvLAfFvX"}
        />,
        props.Title === undefined ? (
          <Title
            key={"SuvZDMdpcu"}
            {...getCompositeDefaultProps("SuvZDMdpcu")}
            id="Title_SuvZDMdpcu"
            className="__visly_reset_7X7HTLRqyD __visly_scope_7dLna7xm52_SuvZDMdpcu"
          />
        ) : (
          <TitleContext.Provider
            key="SuvZDMdpcu-provider"
            value={{
              key: "SuvZDMdpcu",
              id: "Title_SuvZDMdpcu",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_7dLna7xm52_SuvZDMdpcu",
              ...getCompositeDefaultProps("SuvZDMdpcu"),
            }}
          >
            {props.Title}
          </TitleContext.Provider>
        ),
        <SpacerPrimitive
          id={"Spacer_YSKEtySWUK"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_7dLna7xm52_YSKEtySWUK"
          }
          key={"YSKEtySWUK"}
        />,
      ]}
    </RootPrimitive>
  );
}

Header.Title = Title;
Header.__variants = [
  {
    name: "size",
    type: "group",
    variants: ["small", "large", "medium"],
  },
];

export default Header;
