// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./LoadButton.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, IconPrimitive } from "./_internal_primitives";
import * as icons from "./icons";
import { default as RoundButton, RoundButtonContext } from "./RoundButton";

const styles = [
  {
    type: "default",
    layers: {
      JaGHsvRei8: {
        none: {
          icon: icons.chevronDown,
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      V6emB9w3Lf: {},
    },
  },
];

const variantPropTypes = [];

export const LoadButtonContext = createContext(null);

function LoadButton(_props) {
  const defaults = useContext(LoadButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="EMNahkwZWK"
      addSpacing={true}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "EMNahkwZWK",
        scope: "Hf9bqoyJ7r",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.RoundButton === undefined ? (
          <RoundButton
            key={"V6emB9w3Lf"}
            {...getCompositeDefaultProps("V6emB9w3Lf")}
            id="RoundButton_V6emB9w3Lf"
            className="__visly_reset_7X7HTLRqyD __visly_scope_Hf9bqoyJ7r_V6emB9w3Lf"
          />
        ) : (
          <RoundButtonContext.Provider
            key="V6emB9w3Lf-provider"
            value={{
              key: "V6emB9w3Lf",
              id: "RoundButton_V6emB9w3Lf",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_Hf9bqoyJ7r_V6emB9w3Lf",
              ...getCompositeDefaultProps("V6emB9w3Lf"),
            }}
          >
            {props.RoundButton}
          </RoundButtonContext.Provider>
        ),
        <IconPrimitive
          id={"Icon_JaGHsvRei8"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_Hf9bqoyJ7r_JaGHsvRei8"
          }
          key={"JaGHsvRei8"}
          useMask={getStyle("JaGHsvRei8", "useMask")}
          src={getStyle("JaGHsvRei8", "icon")}
        />,
      ]}
    </RootPrimitive>
  );
}

LoadButton.RoundButton = RoundButton;
LoadButton.__variants = [];

export default LoadButton;
