// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./NumInput.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { Root, TextFieldPrimitive } from "./_internal_text_field";

const styles = [
  {
    type: "default",
    layers: {
      input: {
        none: {
          "placeholder-text": "Placeholder",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "small",
  },
];

export const NumInputContext = createContext(null);

function NumInput(_props) {
  const defaults = useContext(NumInputContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <Root
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "root",
        scope: "R2i3hgTWbo",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <TextFieldPrimitive
          id={"input_input"}
          className={"__visly_reset_7X7HTLRqyD __visly_scope_R2i3hgTWbo_input"}
          key={"input"}
          placeholder={
            exists(props.placeholder)
              ? props.placeholder
              : getStyle("input", "placeholder-text")
          }
        />
      )}
    </Root>
  );
}

NumInput.__variants = [
  {
    name: "small",
    type: "variant",
  },
];

export default NumInput;
