// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./SliderValue.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
} from "./_internal_primitives";
import { default as Slider, SliderContext } from "./Slider";

const styles = [
  {
    type: "default",
    layers: {
      "3wWFJiziXq": {
        none: {
          text: "update",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      KZyc3y1rpH: {
        none: {
          secondary: false,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const SliderValueContext = createContext(null);

function SliderValue(_props) {
  const defaults = useContext(SliderValueContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="UvWKy96K3T"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "UvWKy96K3T",
        scope: "UfSgawqYBJ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.Slider === undefined ? (
          <Slider
            key={"KZyc3y1rpH"}
            {...getCompositeDefaultProps("KZyc3y1rpH")}
            id="Slider_KZyc3y1rpH"
            className="__visly_reset_7X7HTLRqyD __visly_scope_UfSgawqYBJ_KZyc3y1rpH"
          />
        ) : (
          <SliderContext.Provider
            key="KZyc3y1rpH-provider"
            value={{
              key: "KZyc3y1rpH",
              id: "Slider_KZyc3y1rpH",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_UfSgawqYBJ_KZyc3y1rpH",
              ...getCompositeDefaultProps("KZyc3y1rpH"),
            }}
          >
            {props.Slider}
          </SliderContext.Provider>
        ),
        <SpacerPrimitive
          id={"Spacer_R4crbfvuHt"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_UfSgawqYBJ_R4crbfvuHt"
          }
          key={"R4crbfvuHt"}
        />,
        <TextPrimitive
          id={"Text_3wWFJiziXq"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_UfSgawqYBJ_3wWFJiziXq"
          }
          key={"3wWFJiziXq"}
          text={
            exists(props.text) ? props.text : getStyle("3wWFJiziXq", "text")
          }
          element={getStyle("3wWFJiziXq", "htmlElement")}
        />,
      ]}
    </RootPrimitive>
  );
}

SliderValue.Slider = Slider;
SliderValue.__variants = [];

export default SliderValue;
