// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./Title.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, TextPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      BtVUJ57pjr: {
        none: {
          text: "euler",
        },
      },
      EPJM6cpWta: {
        none: {
          text: "calc",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const TitleContext = createContext(null);

function Title(_props) {
  const defaults = useContext(TitleContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="CkgJfaZvfX"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "CkgJfaZvfX",
        scope: "6ENjsbjSkJ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <TextPrimitive
            id={"Euler_BtVUJ57pjr"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_6ENjsbjSkJ_BtVUJ57pjr"
            }
            key={"BtVUJ57pjr"}
            text={getStyle("BtVUJ57pjr", "text")}
            element={getStyle("BtVUJ57pjr", "htmlElement")}
          />
          <TextPrimitive
            id={"calc_EPJM6cpWta"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_6ENjsbjSkJ_EPJM6cpWta"
            }
            key={"EPJM6cpWta"}
            text={getStyle("EPJM6cpWta", "text")}
            element={getStyle("EPJM6cpWta", "htmlElement")}
          />
        </>
      )}
    </RootPrimitive>
  );
}

Title.__variants = [];

export default Title;
