// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./fonts.css";
export const button = {
  fontFamily: "Inter, sans-serif",
  fontSize: "16px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "24px",
  textTransform: "none",
};
export const buttonSmall = {
  fontFamily: "Inter, sans-serif",
  fontSize: "12px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "16px",
  textTransform: "none",
};
export const code = {
  fontFamily: "Inter, sans-serif",
  fontSize: "12px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "24px",
  letterSpacing: "0px",
};
export const h1 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "32px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "40px",
  letterSpacing: "-0.32px",
};
export const h2 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "24px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "32px",
  letterSpacing: "0px",
};
export const h3 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "20px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "32px",
  letterSpacing: "0px",
};
export const h4 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "16px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "24px",
  letterSpacing: "0px",
};
export const h5 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "12px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "16px",
  letterSpacing: "0px",
};
export const h6 = {
  fontFamily: "Inter, sans-serif",
  fontSize: "10px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "16px",
  letterSpacing: "0.1px",
};
export const link = {
  fontFamily: "Inter, sans-serif",
  fontSize: "16px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "24px",
  letterSpacing: "0px",
};
export const linkSmall = {
  fontFamily: "Inter, sans-serif",
  fontSize: "12px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "16px",
  letterSpacing: "0px",
};
export const paragraph = {
  fontFamily: "Inter, sans-serif",
  fontSize: "16px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "24px",
  letterSpacing: "0px",
};
export const paragraphLarge = {
  fontFamily: "Inter, sans-serif",
  fontSize: "20px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "32px",
  letterSpacing: "0px",
};
export const paragraphSmall = {
  fontFamily: "Inter, sans-serif",
  fontSize: "12px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "16px",
  letterSpacing: "0.12px",
};
